name: nightary
description: Sleep and Liver Care Management Application
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_localizations:
    sdk: flutter
  collection: any
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.6
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  get: ^4.6.6
  flutter_svg: ^2.0.9
  intl: ^0.18.1
  #based_battery_indicator: ^1.0.3
  based_battery_indicator:
    git:
      url: https://github.com/bunju20/based_widget.git
      path: packages/based_battery_indicator
      ref: master

  carousel_slider: ^4.2.1
  syncfusion_flutter_charts: ^24.1.45
  fl_chart: ^0.66.0
  just_audio: ^0.9.36


  # Custom Time Chart
  path_drawing: ^1.0.1
  touchable: ^1.0.2
  linked_scroll_controller: ^0.2.0

  # Ft Chart
  fl_chart: ^0.66.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  intl_translation: ^0.18.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/config/.env
    - assets/data/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900
