import 'package:nightary/apps/database.dart';
import 'package:nightary/domains/types/e_source.dart';

abstract class DatabaseFactory {
  static NightaryDatabase? _instance;

  static NightaryDatabase get instance => _instance!;

  static Future<void> init() async {
    _instance = NightaryDatabase();
    List<dynamic> temp = await instance.sleepRecordDao.findAll();
    if (temp.isEmpty) {
      await deleteDummyDataInSleepRecord();
      await addDummyDataInSleepRecord();
    }
  }

  static Future<void> deleteDummyDataInSleepRecord() async {
    await instance.delete(instance.sleepRecord).go();
  }

  static Future<void> addDummyDataInSleepRecord() async {
    List<SleepRecordCompanion> sleepRecords = [
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 11, 1, 23, 0),
        endSleepDate: DateTime(2023, 11, 2, 7, 0),
        source: ESource.direct,
        todaySleepDebt: 0,
        totalSleepDebt: 0,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 11, 3, 1, 0),
        endSleepDate: DateTime(2023, 11, 3, 7, 0),
        source: ESource.direct,
        todaySleepDebt: 2,
        totalSleepDebt: 2,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 11, 3, 23, 0),
        endSleepDate: DateTime(2023, 11, 4, 7, 0),
        source: ESource.direct,
        todaySleepDebt: 0,
        totalSleepDebt: 2,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 11, 5, 1, 0),
        endSleepDate: DateTime(2023, 11, 5, 7, 0),
        source: ESource.direct,
        todaySleepDebt: 2,
        totalSleepDebt: 4,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 11, 6, 1, 0),
        endSleepDate: DateTime(2023, 11, 6, 4, 0),
        source: ESource.direct,
        todaySleepDebt: 5,
        totalSleepDebt: 9,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 11, 6, 20, 0),
        endSleepDate: DateTime(2023, 11, 7, 7, 0),
        source: ESource.direct,
        todaySleepDebt: -3,
        totalSleepDebt: 6,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 11, 7, 23, 0),
        endSleepDate: DateTime(2023, 11, 8, 7, 0),
        source: ESource.direct,
        todaySleepDebt: 0,
        totalSleepDebt: 6,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 11, 9, 7, 0),
        endSleepDate: DateTime(2023, 11, 9, 22, 0),
        source: ESource.direct,
        todaySleepDebt: -7,
        totalSleepDebt: 0,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 11, 9, 7, 0),
        endSleepDate: DateTime(2023, 11, 9, 22, 0),
        source: ESource.direct,
        todaySleepDebt: -7,
        totalSleepDebt: 0,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 11, 9, 20, 0),
        endSleepDate: DateTime(2023, 11, 10, 5, 0),
        source: ESource.direct,
        todaySleepDebt: -1,
        totalSleepDebt: 0,
        createdAt: DateTime.now(),
      ),
      // 위까지 10개
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 11, 10, 23, 0),
        endSleepDate: DateTime(2023, 11, 11, 5, 0),
        source: ESource.direct,
        todaySleepDebt: 2,
        totalSleepDebt: 2,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 11, 12, 1, 0),
        endSleepDate: DateTime(2023, 11, 12, 5, 0),
        source: ESource.direct,
        todaySleepDebt: 4,
        totalSleepDebt: 6,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 11, 12, 22, 0),
        endSleepDate: DateTime(2023, 11, 13, 9, 0),
        source: ESource.direct,
        todaySleepDebt: 2,
        totalSleepDebt: 8,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 11, 14, 2, 0),
        endSleepDate: DateTime(2023, 11, 14, 9, 0),
        source: ESource.direct,
        todaySleepDebt: 1,
        totalSleepDebt: 9,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 11, 15, 4, 0),
        endSleepDate: DateTime(2023, 11, 15, 7, 0),
        source: ESource.direct,
        todaySleepDebt: 5,
        totalSleepDebt: 14,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 11, 15, 23, 0),
        endSleepDate: DateTime(2023, 11, 16, 7, 0),
        source: ESource.direct,
        todaySleepDebt: 0,
        totalSleepDebt: 14,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 11, 17, 1, 0),
        endSleepDate: DateTime(2023, 11, 17, 7, 0),
        source: ESource.direct,
        todaySleepDebt: 2,
        totalSleepDebt: 16,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 11, 17, 23, 0),
        endSleepDate: DateTime(2023, 11, 18, 7, 0),
        source: ESource.direct,
        todaySleepDebt: 0,
        totalSleepDebt: 16,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 11, 19, 1, 0),
        endSleepDate: DateTime(2023, 11, 19, 7, 0),
        source: ESource.direct,
        todaySleepDebt: 2,
        totalSleepDebt: 18,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 11, 19, 23, 0),
        endSleepDate: DateTime(2023, 11, 20, 7, 0),
        source: ESource.direct,
        todaySleepDebt: 0,
        totalSleepDebt: 18,
        createdAt: DateTime.now(),
      ),
      // 위까지 20개
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 11, 20, 22, 0),
        endSleepDate: DateTime(2023, 11, 21, 10, 0),
        source: ESource.direct,
        todaySleepDebt: -4,
        totalSleepDebt: 14,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 11, 21, 23, 0),
        endSleepDate: DateTime(2023, 11, 22, 10, 0),
        source: ESource.direct,
        todaySleepDebt: -3,
        totalSleepDebt: 11,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 11, 22, 22, 0),
        endSleepDate: DateTime(2023, 11, 23, 10, 0),
        source: ESource.direct,
        todaySleepDebt: -4,
        totalSleepDebt: 7,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 11, 24, 3, 0),
        endSleepDate: DateTime(2023, 11, 24, 9, 0),
        source: ESource.direct,
        todaySleepDebt: 2,
        totalSleepDebt: 9,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 11, 24, 23, 0),
        endSleepDate: DateTime(2023, 11, 25, 7, 0),
        source: ESource.direct,
        todaySleepDebt: 0,
        totalSleepDebt: 9,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 11, 26, 1, 0),
        endSleepDate: DateTime(2023, 11, 26, 7, 0),
        source: ESource.direct,
        todaySleepDebt: 2,
        totalSleepDebt: 11,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 11, 26, 23, 0),
        endSleepDate: DateTime(2023, 11, 27, 7, 0),
        source: ESource.direct,
        todaySleepDebt: 0,
        totalSleepDebt: 11,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 11, 28, 4, 0),
        endSleepDate: DateTime(2023, 11, 28, 7, 0),
        source: ESource.direct,
        todaySleepDebt: 5,
        totalSleepDebt: 16,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 11, 28, 23, 0),
        endSleepDate: DateTime(2023, 11, 29, 7, 0),
        source: ESource.direct,
        todaySleepDebt: 0,
        totalSleepDebt: 16,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 11, 30, 1, 0),
        endSleepDate: DateTime(2023, 11, 30, 7, 0),
        source: ESource.direct,
        todaySleepDebt: 2,
        totalSleepDebt: 18,
        createdAt: DateTime.now(),
      ),
      // 위까지 30개
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 11, 30, 23, 0),
        endSleepDate: DateTime(2023, 12, 1, 7, 0),
        source: ESource.direct,
        todaySleepDebt: 0,
        totalSleepDebt: 18,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 12, 1, 20, 0),
        endSleepDate: DateTime(2023, 12, 2, 8, 0),
        source: ESource.direct,
        todaySleepDebt: -4,
        totalSleepDebt: 14,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 12, 2, 23, 0),
        endSleepDate: DateTime(2023, 12, 3, 8, 0),
        source: ESource.direct,
        todaySleepDebt: -3,
        totalSleepDebt: 11,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 12, 3, 23, 0),
        endSleepDate: DateTime(2023, 12, 4, 8, 0),
        source: ESource.direct,
        todaySleepDebt: -3,
        totalSleepDebt: 8,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 12, 5, 3, 0),
        endSleepDate: DateTime(2023, 12, 5, 9, 0),
        source: ESource.direct,
        todaySleepDebt: 2,
        totalSleepDebt: 10,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 12, 6, 2, 0),
        endSleepDate: DateTime(2023, 12, 6, 6, 0),
        source: ESource.direct,
        todaySleepDebt: 4,
        totalSleepDebt: 14,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 12, 7, 3, 0),
        endSleepDate: DateTime(2023, 12, 7, 6, 0),
        source: ESource.direct,
        todaySleepDebt: 3,
        totalSleepDebt: 17,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 12, 8, 2, 0),
        endSleepDate: DateTime(2023, 12, 8, 6, 0),
        source: ESource.direct,
        todaySleepDebt: 4,
        totalSleepDebt: 21,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 12, 9, 3, 0),
        endSleepDate: DateTime(2023, 12, 9, 8, 0),
        source: ESource.direct,
        todaySleepDebt: 3,
        totalSleepDebt: 24,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 12, 10, 1, 0),
        endSleepDate: DateTime(2023, 12, 10, 8, 0),
        source: ESource.direct,
        todaySleepDebt: 1,
        totalSleepDebt: 25,
        createdAt: DateTime.now(),
      ),
      // 위까지 40개
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 12, 10, 23, 0),
        endSleepDate: DateTime(2023, 12, 11, 8, 0),
        source: ESource.direct,
        todaySleepDebt: 0,
        totalSleepDebt: 25,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 12, 12, 1, 0),
        endSleepDate: DateTime(2023, 12, 12, 8, 0),
        source: ESource.direct,
        todaySleepDebt: 1,
        totalSleepDebt: 26,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 12, 12, 23, 0),
        endSleepDate: DateTime(2023, 12, 13, 8, 0),
        source: ESource.direct,
        todaySleepDebt: -1,
        totalSleepDebt: 25,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 12, 14, 1, 0),
        endSleepDate: DateTime(2023, 12, 14, 5, 0),
        source: ESource.direct,
        todaySleepDebt: 4,
        totalSleepDebt: 29,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 12, 15, 2, 0),
        endSleepDate: DateTime(2023, 12, 15, 6, 0),
        source: ESource.direct,
        todaySleepDebt: 4,
        totalSleepDebt: 33,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 12, 16, 3, 0),
        endSleepDate: DateTime(2023, 12, 16, 6, 0),
        source: ESource.direct,
        todaySleepDebt: 3,
        totalSleepDebt: 36,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 12, 17, 2, 0),
        endSleepDate: DateTime(2023, 12, 17, 6, 0),
        source: ESource.direct,
        todaySleepDebt: 4,
        totalSleepDebt: 40,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 12, 17, 22, 0),
        endSleepDate: DateTime(2023, 12, 18, 8, 0),
        source: ESource.direct,
        todaySleepDebt: -2,
        totalSleepDebt: 38,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 12, 18, 20, 0),
        endSleepDate: DateTime(2023, 12, 19, 12, 0),
        source: ESource.direct,
        todaySleepDebt: -8,
        totalSleepDebt: 30,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 12, 20, 3, 0),
        endSleepDate: DateTime(2023, 12, 20, 6, 0),
        source: ESource.direct,
        todaySleepDebt: 3,
        totalSleepDebt: 33,
        createdAt: DateTime.now(),
      ),
      // 위까지 50개
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 12, 20, 23, 0),
        endSleepDate: DateTime(2023, 12, 21, 8, 0),
        source: ESource.direct,
        todaySleepDebt: -1,
        totalSleepDebt: 32,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 12, 22, 1, 0),
        endSleepDate: DateTime(2023, 12, 22, 8, 0),
        source: ESource.direct,
        todaySleepDebt: 1,
        totalSleepDebt: 33,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 12, 22, 23, 0),
        endSleepDate: DateTime(2023, 12, 23, 8, 0),
        source: ESource.direct,
        todaySleepDebt: -1,
        totalSleepDebt: 32,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 12, 24, 1, 0),
        endSleepDate: DateTime(2023, 12, 24, 8, 0),
        source: ESource.direct,
        todaySleepDebt: 1,
        totalSleepDebt: 33,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 12, 24, 23, 0),
        endSleepDate: DateTime(2023, 12, 25, 8, 0),
        source: ESource.direct,
        todaySleepDebt: -1,
        totalSleepDebt: 32,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 12, 25, 20, 0),
        endSleepDate: DateTime(2023, 12, 26, 12, 0),
        source: ESource.direct,
        todaySleepDebt: -8,
        totalSleepDebt: 24,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 12, 27, 1, 0),
        endSleepDate: DateTime(2023, 12, 27, 11, 0),
        source: ESource.direct,
        todaySleepDebt: -2,
        totalSleepDebt: 25,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 12, 27, 23, 0),
        endSleepDate: DateTime(2023, 12, 28, 10, 0),
        source: ESource.direct,
        todaySleepDebt: -3,
        totalSleepDebt: 22,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 12, 28, 22, 0),
        endSleepDate: DateTime(2023, 12, 29, 10, 0),
        source: ESource.direct,
        todaySleepDebt: -4,
        totalSleepDebt: 18,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 12, 29, 23, 0),
        endSleepDate: DateTime(2023, 12, 30, 10, 0),
        source: ESource.direct,
        todaySleepDebt: -3,
        totalSleepDebt: 15,
        createdAt: DateTime.now(),
      ),
      // 위까지 60개
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 12, 31, 1, 0),
        endSleepDate: DateTime(2023, 12, 31, 10, 0),
        source: ESource.direct,
        todaySleepDebt: -1,
        totalSleepDebt: 14,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2023, 12, 31, 23, 0),
        endSleepDate: DateTime(2024, 1, 1, 12, 0),
        source: ESource.direct,
        todaySleepDebt: -5,
        totalSleepDebt: 9,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2024, 1, 2, 1, 0),
        endSleepDate: DateTime(2024, 1, 2, 10, 0),
        source: ESource.direct,
        todaySleepDebt: -1,
        totalSleepDebt: 8,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2024, 1, 2, 23, 0),
        endSleepDate: DateTime(2024, 1, 3, 10, 0),
        source: ESource.direct,
        todaySleepDebt: -3,
        totalSleepDebt: 5,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2024, 1, 4, 3, 32),
        endSleepDate: DateTime(2024, 1, 4, 6, 32),
        source: ESource.direct,
        todaySleepDebt: 5,
        totalSleepDebt: 10,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2024, 1, 5, 2, 0),
        endSleepDate: DateTime(2024, 1, 5, 7, 0),
        source: ESource.direct,
        todaySleepDebt: 3,
        totalSleepDebt: 13,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2024, 1, 6, 1, 0),
        endSleepDate: DateTime(2024, 1, 6, 2, 0),
        source: ESource.direct,
        todaySleepDebt: 7,
        totalSleepDebt: 20,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2024, 1, 7, 1, 0),
        endSleepDate: DateTime(2024, 1, 7, 5, 0),
        source: ESource.direct,
        todaySleepDebt: 4,
        totalSleepDebt: 24,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2024, 1, 8, 10, 0),
        endSleepDate: DateTime(2024, 1, 8, 16, 0),
        source: ESource.direct,
        todaySleepDebt: 2,
        totalSleepDebt: 26,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2024, 1, 8, 8, 0),
        endSleepDate: DateTime(2024, 1, 9, 15, 0),
        source: ESource.direct,
        todaySleepDebt: 1,
        totalSleepDebt: 27,
        createdAt: DateTime.now(),
      ),
      // 위까지 70개
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2024, 1, 10, 6, 0),
        endSleepDate: DateTime(2024, 1, 10, 10, 0),
        source: ESource.direct,
        todaySleepDebt: 4,
        totalSleepDebt: 31,
        createdAt: DateTime.now(),
      ),
      SleepRecordCompanion.insert(
        startSleepDate: DateTime(2024, 1, 11, 8, 0),
        endSleepDate: DateTime(2024, 1, 11, 12, 0),
        source: ESource.direct,
        todaySleepDebt: 4,
        totalSleepDebt: 35,
        createdAt: DateTime.now(),
      ),
    ];

    await instance.sleepRecordDao.saveAll(sleepRecords);
  }
}
